import { describe, it, expect } from "vitest"
import { tokenizeCsv, ImportFormatError } from "./tokenize"

// Real 16-column header from a Swedish HR export.
const HEADER =
  "Anstallningsdatum;Fornamn;Efternamn;Chef;Kon;Land;Löneår;Födelsedatum;Befattning;Statistikkod;Månadslön;Tjänstebil;Målbonus;Valuta;Anstnr;Sysselssättningsgrad"

// Fixture: UTF-8 BOM + semicolon-delimited, one data row with a quoted field
// containing a semicolon, followed by a blank trailing line.
const BOM = "﻿"
const FIXTURE =
  BOM +
  HEADER +
  "\n" +
  '2023-01-15;Anna;Svensson;Ja;Kvinna;Sverige;2024;1990-05-20;"Chefsassistent; med ansvar";12345;52000;0;5000;SEK;EMP001;100\n' +
  "\n" // blank trailing line

describe("tokenizeCsv", () => {
  it("strips the BOM and returns 16 headers", () => {
    const { headers } = tokenizeCsv(FIXTURE)
    expect(headers.length).toBe(16)
  })

  it("returns the correct header names in order", () => {
    const { headers } = tokenizeCsv(FIXTURE)
    const expected = HEADER.split(";")
    expect(headers).toEqual(expected)
  })

  it("drops the blank trailing line (rows contains only data rows)", () => {
    const { rows } = tokenizeCsv(FIXTURE)
    expect(rows.length).toBe(1)
  })

  it("treats the quoted field with an embedded semicolon as a single cell", () => {
    const { rows } = tokenizeCsv(FIXTURE)
    const dataRow = rows[0]
    if (!dataRow) throw new Error("expected a data row")
    // "Chefsassistent; med ansvar" is one cell (index 8)
    expect(dataRow[8]).toBe("Chefsassistent; med ansvar")
    // and the row has exactly 16 cells
    expect(dataRow.length).toBe(16)
  })
})

describe("tokenizeCsv line-ending normalization (T08, T09, T10, T11)", () => {
  it("handles CRLF header then LF data (T08)", () => {
    const { rows } = tokenizeCsv("name,salary\r\nAlice,50000\nBob,60000")
    expect(rows.length).toBe(2)
    expect(rows[0]).toEqual(["Alice", "50000"])
    expect(rows[1]).toEqual(["Bob", "60000"])
  })

  it("handles LF header then CRLF data with no stray CR (T09)", () => {
    const { rows } = tokenizeCsv("name,salary\nAlice,50000\r\nBob,60000")
    expect(rows[0]?.[1]).toBe("50000")
    expect(JSON.stringify(rows)).not.toContain("\\r")
  })

  it("handles lone CR line endings (T11)", () => {
    const { headers, rows } = tokenizeCsv("name,salary\rAlice,50000\rBob,60000")
    expect(headers).toEqual(["name", "salary"])
    expect(rows.length).toBe(2)
  })
})

describe("tokenizeCsv sep= directive (T12, T13, T14, T39, T40)", () => {
  it("consumes sep=; and uses the declared delimiter (T12)", () => {
    const { headers, signals } = tokenizeCsv("sep=;\nNamn;Lon\nAnna;52000")
    expect(headers).toEqual(["Namn", "Lon"])
    expect(signals.preambleRowsSkipped).toBe(0) // sep= is a directive, not a preamble row
  })

  it("consumes sep=, (T13)", () => {
    const { headers } = tokenizeCsv("sep=,\nname,salary\nAnna,52000")
    expect(headers).toEqual(["name", "salary"])
  })

  it("consumes sep=<TAB> (T14)", () => {
    const { headers } = tokenizeCsv("sep=\t\nname\tsalary\nAnna\t52000")
    expect(headers).toEqual(["name", "salary"])
  })

  it("strips a BOM then consumes sep=; (T39)", () => {
    const { headers } = tokenizeCsv("﻿sep=;\nNamn;Lon\nAnna;52000")
    expect(headers).toEqual(["Namn", "Lon"])
  })

  it("falls back to auto-detect when the declared delimiter is absent from data (T40)", () => {
    const { headers } = tokenizeCsv("sep=|\nname,salary\nAnna,52000")
    expect(headers).toEqual(["name", "salary"])
  })
})

describe("tokenizeCsv preamble / metadata / hash skipping (T15, T16, T34)", () => {
  it("skips a single-cell title preamble row (T15)", () => {
    const { headers, signals } = tokenizeCsv(
      "Lonerapport 2024 Q1\nNamn,Lon,Avd\nAnna,52000,IT\nErik,61000,HR"
    )
    expect(headers).toEqual(["Namn", "Lon", "Avd"])
    expect(signals.preambleRowsSkipped).toBe(1)
  })

  it("skips multi-line metadata preamble (T16)", () => {
    const { headers, signals } = tokenizeCsv(
      "Foretag: Acme AB\nPeriod: 2024-03\nNamn;Lon;Avd\nAnna;52000;IT\nErik;61000;HR"
    )
    expect(headers).toEqual(["Namn", "Lon", "Avd"])
    expect(signals.preambleRowsSkipped).toBe(2)
  })

  it("skips a leading hash-comment row (T34)", () => {
    const { headers, signals } = tokenizeCsv(
      "# Generated by Visma Lon\nNamn,Lon,Avd\nAnna,52000,IT\nErik,61000,HR"
    )
    expect(headers).toEqual(["Namn", "Lon", "Avd"])
    expect(signals.preambleRowsSkipped).toBe(1)
  })

  it("does NOT skip anything in a clean file", () => {
    const { headers, signals } = tokenizeCsv(
      "name,salary\nAlice,50000\nBob,60000"
    )
    expect(headers).toEqual(["name", "salary"])
    expect(signals.preambleRowsSkipped).toBe(0)
  })
})

describe("tokenizeCsv trailing empty column strip (T18)", () => {
  it("strips a trailing all-empty column with a blank header", () => {
    const { headers, rows } = tokenizeCsv(
      "name,salary,dept,\nAlice,50000,IT,\nBob,60000,HR,"
    )
    expect(headers).toEqual(["name", "salary", "dept"])
    expect(rows[0]).toEqual(["Alice", "50000", "IT"])
  })
})

describe("tokenizeCsv ragged-row normalization (T19, T20)", () => {
  it("pads a short row to header width and records it (T19)", () => {
    const { rows, signals } = tokenizeCsv(
      "id,name,salary,dept\n1,Alice\n2,Bob,60000,HR"
    )
    expect(rows[0]).toEqual(["1", "Alice", "", ""])
    expect(signals.raggedRows).toContain(0)
  })

  it("truncates a long row to header width and records it (T20)", () => {
    const { rows, signals } = tokenizeCsv("id,name\n1,Alice,extra\n2,Bob")
    expect(rows[0]).toEqual(["1", "Alice"])
    expect(signals.raggedRows).toContain(0)
  })
})

describe("tokenizeCsv duplicate / blank headers (T21, T22)", () => {
  it("disambiguates duplicate header names and records them (T21)", () => {
    const { headers, signals } = tokenizeCsv(
      "name,salary,salary,dept\nAlice,50000,55000,IT"
    )
    expect(headers).toEqual(["name", "salary", "salary_2", "dept"])
    expect(signals.duplicateHeaders).toContain("salary")
  })

  it("preserves a blank mid-row header as a stable column and records it (T22)", () => {
    const { headers, signals } = tokenizeCsv(
      "name,,salary,dept\nAlice,x,50000,IT"
    )
    expect(headers.length).toBe(4)
    expect(headers[1]).toBe("")
    expect(signals.blankHeaderColumns).toContain(1)
  })
})

describe("tokenizeCsv header trimming and null-byte cleanup (T23, T35)", () => {
  it("trims whitespace-padded headers (T23)", () => {
    const { headers } = tokenizeCsv("  name  ,  salary  \nAlice,50000")
    expect(headers).toEqual(["name", "salary"])
  })

  it("strips null bytes from values (T35)", () => {
    const { rows } = tokenizeCsv("name,salary\nAlice\0,50000")
    expect(rows[0]?.[0]).toBe("Alice")
  })
})

describe("tokenizeCsv binary-signature guard (A1, A2, A3)", () => {
  it("throws ImportFormatError with kind binary and signature zip for XLSX/ODS (A1, A3)", () => {
    const xlsx = "PK\x03\x04" + "rest-of-zip-bytes"
    expect(() => tokenizeCsv(xlsx)).toThrow(ImportFormatError)
    try {
      tokenizeCsv(xlsx)
    } catch (e) {
      expect(e).toBeInstanceOf(ImportFormatError)
      const err = e as ImportFormatError
      expect(err.kind).toBe("binary")
      expect(err.signature).toBe("zip")
      expect(err.name).toBe("ImportFormatError")
    }
  })

  it("throws ImportFormatError with signature ole2 for legacy XLS (A2)", () => {
    const xls = "\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1" + "rest-of-ole2"
    try {
      tokenizeCsv(xls)
      throw new Error("expected tokenizeCsv to throw")
    } catch (e) {
      expect(e).toBeInstanceOf(ImportFormatError)
      expect((e as ImportFormatError).signature).toBe("ole2")
    }
  })

  it("does NOT throw for a normal CSV that merely contains PK later", () => {
    // A CSV value containing "PK" mid-line must not trip the leading-byte guard.
    expect(() => tokenizeCsv("name,code\nAlice,PK1234\nBob,ZZ99")).not.toThrow()
  })

  it("does NOT throw for a CSV whose first field starts with the letters PK", () => {
    // Real header text can start with letters; only the exact PK\x03\x04 magic trips it.
    expect(() => tokenizeCsv("PKlevel,salary\nA,50000")).not.toThrow()
  })
})

describe("tokenizeCsv disambiguation collision-proof (CORRECTNESS FIX 2)", () => {
  it("produces three distinct names when 'salary','salary','salary_2' appear together", () => {
    // Input: salary (col 0), salary (col 1, duplicate), salary_2 (col 2, explicit).
    // Naive _2 suffix would collide with the explicit salary_2 column.
    // The fix must skip _2 (already taken) and use _3 for the disambiguated duplicate.
    const { headers, signals } = tokenizeCsv(
      "salary,salary,salary_2\n50000,55000,52000"
    )
    // All three names must be distinct.
    const unique = new Set(headers)
    expect(unique.size).toBe(3)
    // The original explicit salary_2 must be preserved at its position (index 2).
    expect(headers[2]).toBe("salary_2")
    // The duplicate (index 1) must have been given a different suffix.
    expect(headers[1]).not.toBe("salary_2")
    expect(headers[1]).not.toBe("salary") // must have been renamed
    // The duplicate signal must still record the original collision name.
    expect(signals.duplicateHeaders).toContain("salary")
  })
})

describe("tokenizeCsv single-column signal (T38)", () => {
  it("flags a space-only pseudo-CSV as noDelimiter", () => {
    const { headers, signals } = tokenizeCsv(
      "employee salary department\nAlice 50000 IT"
    )
    expect(headers.length).toBe(1)
    expect(signals.noDelimiter).toBe(true)
  })

  it("does NOT flag a normal multi-column file", () => {
    const { signals } = tokenizeCsv("name,salary\nAlice,50000")
    expect(signals.noDelimiter).toBe(false)
  })
})

describe("tokenizeCsv headerless detection (HL)", () => {
  const DATA_ROWS = [
    "1001;Anna Svensson;Kvinna;Utvecklare;IT;2020-01-15;100;52000",
    "1002;Erik Johansson;Man;Controller;Ekonomi;2018-03-01;80;48500",
    "1003;Maria Karlsson;Kvinna;HR-specialist;HR;2021-09-01;100;44000",
  ]

  it("HL-01: flags a headerless payroll file and keeps every row as data", () => {
    const result = tokenizeCsv(DATA_ROWS.join("\n"))
    expect(result.signals.headerless).toBe(true)
    expect(result.rows.length).toBe(3)
    expect(result.rows[0]?.[1]).toBe("Anna Svensson")
  })

  it("HL-02: synthesizes unique positional header names", () => {
    const result = tokenizeCsv(DATA_ROWS.join("\n"))
    expect(result.headers).toEqual([
      "column_1",
      "column_2",
      "column_3",
      "column_4",
      "column_5",
      "column_6",
      "column_7",
      "column_8",
    ])
    // Headerless is its own signal: no blank/duplicate header noise.
    expect(result.signals.blankHeaderColumns).toEqual([])
    expect(result.signals.duplicateHeaders).toEqual([])
  })

  it("HL-03: one recognized header synonym keeps the header interpretation", () => {
    const csv = ["Anstnr;Namn;Kon;Titel", "1001;Anna;Kvinna;Utvecklare"].join(
      "\n"
    )
    const result = tokenizeCsv(csv)
    expect(result.signals.headerless).toBe(false)
    expect(result.rows.length).toBe(1)
  })

  it("HL-04: unknown all-text headers stay headers (no data-shape signal)", () => {
    const csv = [
      "EmployeeNo;FullName;Sex;JobTitle;Unit",
      "1001;Anna Svensson;Kvinna;Utvecklare;IT",
    ].join("\n")
    const result = tokenizeCsv(csv)
    expect(result.signals.headerless).toBe(false)
    expect(result.headers[0]).toBe("EmployeeNo")
  })

  it("HL-05: a single-row file cannot be judged and keeps the status quo", () => {
    const result = tokenizeCsv(DATA_ROWS[0] as string)
    expect(result.signals.headerless).toBe(false)
  })

  it("HL-06: headerless detection still applies after a preamble comment", () => {
    const csv = ["# export 2026-07-09", ...DATA_ROWS].join("\n")
    const result = tokenizeCsv(csv)
    expect(result.signals.headerless).toBe(true)
    expect(result.rows.length).toBe(3)
    expect(result.signals.preambleRowsSkipped).toBe(1)
  })

  it("HL-07: a headered file reports headerless: false in signals", () => {
    const csv = ["Anstnr;Namn", "1;Anna"].join("\n")
    expect(tokenizeCsv(csv).signals.headerless).toBe(false)
  })
})
